---

#[prime.](access.redhat.com/documentation/en-us/red_hat_virtualization/4.1/html/installation_guide/appe-configuring_a_hypervisor_host_for_pci_passthrough)
- name: Allow unsafe interrupts allow_unsafe_interrupts=1
  become: true
  lineinfile:
    path: /etc/modprobe.d/iommu_unsafe_interrupts.conf
    create: yes
    line: 'options vfio_iommu_type1 allow_unsafe_interrupts=1'
  notify: dracut regenerate
